### ISSUE TITLE
[BUG] Blank Icon

### ISSUE THREAD

**Issue by Crowguard** [averrin/director#5]
**Module Version:** v1.0.0

**Describe the bug**
The icon in the Tiles layer is now missing an icon.

![image](https://user-images.githubusercontent.com/99844555/201005454-d2e1c3b8-ebb8-46cf-960f-f2104d0e2154.png)

**Browser:**
 - Firefox

**Foundry Version:** 

10.288

**Game System:** 

D&D 5e

**Additional context**
Forge hosting

**Comment by averrin** [comment]
Hi.
1. What place is it? Tiles layer or Alpha one?
2. What OS do you use? This icon is emoji, so it should be supported by your font. I didnt encountered a case when foundry fonts fails to show this icon. Maybe its because of some custom font 

I dont have this issue on linux/windows in firefox/chrome/vivaldi...

**Comment by averrin** [comment]
But, I decided to change icon from emoji to `fa`s

**Comment by Crowguard** [comment]
Tiles layer icon.

Windows, Firefox.

The icon used to be there. Not entirely sure when it disappeared.

**Comment by Truncated** [comment]
It's gone in Chrome as well.

**Comment by averrin** [comment]
According to another your issue, it can be because all styles broken by some reason. But I'll release fix of he icon in a day or two. I have a quite busy week...

**Comment by averrin** [comment]
I released the update. I suppose it's fixed

**Comment by Truncated** [comment]
It's back in Chrome:
![image](https://user-images.githubusercontent.com/14208325/204112112-dfd8eecd-1bee-4e71-bf25-d8c02a4b6741.png)
